pr1 : 
https://leetcode.com/problems/big-countries/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [1]:
import pandas as pd

In [2]:
data = [['Afghanistan', 'Asia', 652230, 25500100, 20343000000], ['Albania', 'Europe', 28748, 2831741, 12960000000], ['Algeria', 'Africa', 2381741, 37100000, 188681000000], ['Andorra', 'Europe', 468, 78115, 3712000000], ['Angola', 'Africa', 1246700, 20609294, 100990000000]]
world = pd.DataFrame(data, columns=['name', 'continent', 'area', 'population', 'gdp']).astype({'name':'object', 'continent':'object', 'area':'Int64', 'population':'Int64', 'gdp':'Int64'})

In [3]:
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    return world.query('area >= 3000000 or population>=25000000')[['name','population','area']]

big_countries(world)

          name  population     area
0  Afghanistan    25500100   652230
2      Algeria    37100000  2381741

pr2:
https://leetcode.com/problems/recyclable-and-low-fat-products/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [4]:
data = [['0', 'Y', 'N'], ['1', 'Y', 'Y'], ['2', 'N', 'Y'], ['3', 'Y', 'Y'], ['4', 'N', 'N']]
products = pd.DataFrame(data, columns=['product_id', 'low_fats', 'recyclable']).astype({'product_id':'int64', 'low_fats':'category', 'recyclable':'category'})

In [5]:
def find_products(products: pd.DataFrame) -> pd.DataFrame:
    return products.query('low_fats=="Y" and recyclable=="Y"')[['product_id']]

find_products(products)

   product_id
1           1
3           3