pr1 : 
https://leetcode.com/problems/big-countries/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [1]:
import pandas as pd

In [2]:
data = [['Afghanistan', 'Asia', 652230, 25500100, 20343000000], ['Albania', 'Europe', 28748, 2831741, 12960000000], ['Algeria', 'Africa', 2381741, 37100000, 188681000000], ['Andorra', 'Europe', 468, 78115, 3712000000], ['Angola', 'Africa', 1246700, 20609294, 100990000000]]
world = pd.DataFrame(data, columns=['name', 'continent', 'area', 'population', 'gdp']).astype({'name':'object', 'continent':'object', 'area':'Int64', 'population':'Int64', 'gdp':'Int64'})

In [3]:
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    return world.query('area >= 3000000 or population>=25000000')[['name','population','area']]

big_countries(world)

          name  population     area
0  Afghanistan    25500100   652230
2      Algeria    37100000  2381741

pr2:
https://leetcode.com/problems/recyclable-and-low-fat-products/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [4]:
data = [['0', 'Y', 'N'], ['1', 'Y', 'Y'], ['2', 'N', 'Y'], ['3', 'Y', 'Y'], ['4', 'N', 'N']]
products = pd.DataFrame(data, columns=['product_id', 'low_fats', 'recyclable']).astype({'product_id':'int64', 'low_fats':'category', 'recyclable':'category'})

In [5]:
def find_products(products: pd.DataFrame) -> pd.DataFrame:
    return products.query('low_fats=="Y" and recyclable=="Y"')[['product_id']]

find_products(products)

   product_id
1           1
3           3

pr3:
 https://leetcode.com/problems/customers-who-never-order/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [6]:
data = [[1, 'Joe'], [2, 'Henry'], [3, 'Sam'], [4, 'Max']]
customers = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})
data = [[1, 3], [2, 1]]
orders = pd.DataFrame(data, columns=['id', 'customerId']).astype({'id':'Int64', 'customerId':'Int64'})

In [7]:
def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    customer_order = orders["customerId"]
    return customers.query('id not in @customer_order')[['name']].rename(columns={'name':'Customers'})

find_customers(customers, orders)

  Customers
1     Henry
3       Max

pr4:
https://leetcode.com/problems/article-views-i/description/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [8]:
data = [[1, 3, 5, '2019-08-01'], [1, 3, 6, '2019-08-02'], [2, 7, 7, '2019-08-01'], [2, 7, 6, '2019-08-02'], [4, 7, 1, '2019-07-22'], [3, 4, 4, '2019-07-21'], [3, 4, 4, '2019-07-21']]
views = pd.DataFrame(data, columns=['article_id', 'author_id', 'viewer_id', 'view_date']).astype({'article_id':'Int64', 'author_id':'Int64', 'viewer_id':'Int64', 'view_date':'datetime64[ns]'})

In [9]:
def article_views(views: pd.DataFrame) -> pd.DataFrame:
    return views.query('author_id==viewer_id')[['author_id']].rename(columns={'author_id':'id'}).drop_duplicates().sort_values('id')

article_views(views)

   id
5   4
2   7

pr5:
https://leetcode.com/problems/invalid-tweets/

In [10]:
data = [[1, 'Let us Code'], [2, 'More than fifteen chars are here!']]
tweets = pd.DataFrame(data, columns=['tweet_id', 'content']).astype({'tweet_id':'Int64', 'content':'object'})

In [11]:
def invalid_tweets(tweets: pd.DataFrame) -> pd.DataFrame:
    return tweets.query('content.str.len()>15')[['tweet_id']]

invalid_tweets(tweets)

   tweet_id
1         2

pr6:
https://leetcode.com/problems/calculate-special-bonus/

In [12]:
data = [[2, 'Meir', 3000], [3, 'Michael', 3800], [7, 'Addilyn', 7400], [8, 'Juan', 6100], [9, 'Kannon', 7700]]
employees = pd.DataFrame(data, columns=['employee_id', 'name', 'salary']).astype({'employee_id':'int64', 'name':'object', 'salary':'int64'})

In [13]:
def calculate_special_bonus(employees: pd.DataFrame) -> pd.DataFrame:
    employees['bonus'] = employees.\
        apply(lambda emp: emp['salary'] if (emp['employee_id']%2!=0 ) & (~emp['name'].startswith('M')) else 0,axis=1)
    return employees[['employee_id','bonus']].sort_values('employee_id')

calculate_special_bonus(employees)

   employee_id  bonus
0            2      0
1            3      0
2            7   7400
3            8      0
4            9   7700

pr7:
https://leetcode.com/problems/fix-names-in-a-table/submissions/2054351713/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [14]:
data = [[1, 'aLice'], [2, 'bOB']]
users = pd.DataFrame(data, columns=['user_id', 'name']).astype({'user_id':'Int64', 'name':'object'})

In [16]:
def fix_names(users: pd.DataFrame) -> pd.DataFrame:
    users['name'] = users['name'].apply(lambda val:val[0].upper() + val[1:].lower())
    return users[["user_id","name"]].\
    sort_values('user_id') # type: ignore

fix_names(users)

   user_id   name
0        1  Alice
1        2    Bob

pr8:
https://leetcode.com/problems/find-users-with-valid-e-mails/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [17]:
data = [[1, 'Winston', 'winston@leetcode.com'], [2, 'Jonathan', 'jonathanisgreat'], [3, 'Annabelle', 'bella-@leetcode.com'], [4, 'Sally', 'sally.come@leetcode.com'], [5, 'Marwan', 'quarz#2020@leetcode.com'], [6, 'David', 'david69@gmail.com'], [7, 'Shapiro', '.shapo@leetcode.com']]
users = pd.DataFrame(data, columns=['user_id', 'name', 'mail']).astype({'user_id':'int64', 'name':'object', 'mail':'object'})

In [18]:
def valid_emails(users: pd.DataFrame) -> pd.DataFrame:
    return users[users['mail'].str.match(r'^[A-Za-z][A-Za-z0-9_.-]*@leetcode.com$')]

valid_emails(users)

   user_id       name                     mail
0        1    Winston     winston@leetcode.com
2        3  Annabelle      bella-@leetcode.com
3        4      Sally  sally.come@leetcode.com

pr9:
https://leetcode.com/problems/patients-with-a-condition/submissions/2055274297/

In [19]:
data = [[1, 'Daniel', 'YFEV COUGH'], [2, 'Alice', ''], [3, 'Bob', 'DIAB100 MYOP'], [4, 'George', 'ACNE DIAB100'], [5, 'Alain', 'DIAB201']]
patients = pd.DataFrame(data, columns=['patient_id', 'patient_name', 'conditions']).astype({'patient_id':'int64', 'patient_name':'object', 'conditions':'object'})

In [20]:
def find_patients(patients: pd.DataFrame) -> pd.DataFrame:
    return patients[patients['conditions'].str.startswith('DIAB1') | patients['conditions'].str.contains(' DIAB1') ]

find_patients(patients)

   patient_id patient_name    conditions
2           3          Bob  DIAB100 MYOP
3           4       George  ACNE DIAB100

pr10:
https://leetcode.com/problems/rearrange-products-table/submissions/2055314664/

In [21]:
data = [[0, 95, 100, 105], [1, 70, None, 80]]
products = pd.DataFrame(data, columns=['product_id', 'store1', 'store2', 'store3']).astype({'product_id':'Int64', 'store1':'Int64', 'store2':'Int64', 'store3':'Int64'})

In [23]:
def rearrange_products_table(products: pd.DataFrame) -> pd.DataFrame:
    return products.melt(
        id_vars='product_id',
        var_name='store',
        value_name='price'
    ).dropna()

rearrange_products_table(products)

   product_id   store  price
0           0  store1     95
1           1  store1     70
2           0  store2    100
4           0  store3    105
5           1  store3     80

pr11:
https://leetcode.com/problems/delete-duplicate-emails/submissions/2055323388/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [24]:
data = [[1, 'john@example.com'], [2, 'bob@example.com'], [3, 'john@example.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id':'int64', 'email':'object'})

In [25]:
def delete_duplicate_emails(person: pd.DataFrame) -> None:
    person.sort_values('id',inplace=True)
    person.drop_duplicates(subset='email',keep='first',inplace=True)

delete_duplicate_emails(person)

pr12:
https://leetcode.com/problems/find-total-time-spent-by-each-employee/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [26]:
data = [['1', '2020-11-28', '4', '32'], ['1', '2020-11-28', '55', '200'], ['1', '2020-12-3', '1', '42'], ['2', '2020-11-28', '3', '33'], ['2', '2020-12-9', '47', '74']]
employees = pd.DataFrame(data, columns=['emp_id', 'event_day', 'in_time', 'out_time']).astype({'emp_id':'Int64', 'event_day':'datetime64[ns]', 'in_time':'Int64', 'out_time':'Int64'})

In [28]:

def total_time(employees: pd.DataFrame) -> pd.DataFrame:
    employees['total'] = employees['out_time']-employees['in_time']
    return employees.\
        groupby(['event_day','emp_id']).\
        agg(total_time=('total','sum')).\
        reset_index().\
        rename(columns={'event_day':'day'})
    
total_time(employees)

         day  emp_id  total_time
0 2020-11-28       1         173
1 2020-11-28       2          30
2 2020-12-03       1          41
3 2020-12-09       2          27

# .groupby(...).agg(new_name=('col', 'count'))
pr13:
https://leetcode.com/problems/daily-leads-and-partners/?envType=study-plan-v2&envId=30-days-of-pandas&lang=pythondata

In [31]:
data = [['2020-12-8', 'toyota', 0, 1], ['2020-12-8', 'toyota', 1, 0], ['2020-12-8', 'toyota', 1, 2], ['2020-12-7', 'toyota', 0, 2], ['2020-12-7', 'toyota', 0, 1], ['2020-12-8', 'honda', 1, 2], ['2020-12-8', 'honda', 2, 1], ['2020-12-7', 'honda', 0, 1], ['2020-12-7', 'honda', 1, 2], ['2020-12-7', 'honda', 2, 1]]
daily_sales = pd.DataFrame(data, columns=['date_id', 'make_name', 'lead_id', 'partner_id']).astype({'date_id':'datetime64[ns]', 'make_name':'object', 'lead_id':'Int64', 'partner_id':'Int64'})

In [32]:
def daily_leads_and_partners(daily_sales: pd.DataFrame) -> pd.DataFrame:
    return daily_sales.\
        groupby(['date_id','make_name']).\
        agg(unique_leads=('lead_id','nunique'),unique_partners=('partner_id','nunique')).\
        reset_index()

daily_leads_and_partners(daily_sales)

     date_id make_name  unique_leads  unique_partners
0 2020-12-07     honda             3                2
1 2020-12-07    toyota             1                2
2 2020-12-08     honda             2                2
3 2020-12-08    toyota             2                3